# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = ["defaults" "size=2048M" "mode=755"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/2f8d3293-769a-4c33-b57f-9194ccac77a7";
    fsType = "bcachefs";
    neededForBoot = true;
    options = ["X-mount.mkdir"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/78CD-FBD8";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022" "X-mount.mkdir"];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/e264e41d-75b0-4749-9f0b-ed3e86aee1b2";
      randomEncryption.enable = true;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
