# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &a4blue 0949AD16A796430A17DA745B935AE16BC6A4D9B9
  - &homelab_iteration_11 age1khu90gj74f2y3cxldl6qsa3pv3uv82h8w395dc9vtute9ckzmc9qq0dmdh
  - &diy_pc_wsl2 age19aq3kpwursrz4tydp8jjhdzy7ud4kvw5shq4n7kr8hzrgdkp35gqtv48u7
  - &diy_pc_wsl2_ubuntu_2404 age13gxhv0qtedhzg9l9qxhzsvgh0vme6vgzr7sugfs92x0cg259jsgq8w87tx
  - &diy_pc_wsl2_nixos age14jjaupqzcnrp48nlq9mhycafwpfn6wpj7f7vk6mnfur0dgyhvf0s5m9yc0
  - &diy_pc_wsl2_nixos_a4blue age1qay9dnyfe036cum0wygdjhurfjytjgenp5eagxmq66tsqd08cg8spu975c
  - &diy_pc_nixos age1vcxd930l6hwfunalzy8s0yaawg8rpst70fp4nzwrkn7g8ssjyucsz8sr4g
  - &laptop_nix_initrd age1nu6e3xj8rlnyjda848g60u6ljyp5s62qt9lfmk7ytqha83xnyf8q9mee48
  - &laptop_nix_initrd_2024 age1vscc45869s7j897q349gzelr3f0yqp8kf3ly2dnknph706cctvmqy4vwer
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *a4blue
      age:
      - *diy_pc_wsl2
      - *homelab_iteration_11
      - *diy_pc_wsl2_ubuntu_2404
      - *diy_pc_wsl2_nixos
      - *diy_pc_wsl2_nixos_a4blue
      - *diy_pc_nixos
      - *laptop_nix_initrd
      - *laptop_nix_initrd_2024